controller_list:
  - name: fake_arm_left_controller
    joints:
      - arm_shoulder_left_roll
      - arm_shoulder_left_pitch
      - arm_elbow_left_yaw
      - arm_elbow_left_roll
  - name: fake_arm_right_controller
    joints:
      - arm_shoulder_right_roll
      - arm_shoulder_right_pitch
      - arm_elbow_right_yaw
      - arm_elbow_right_roll
  - name: fake_gripper_right_controller
    joints:
      - arm_wrist_right_yaw
  - name: fake_gripper_left_controller
    joints:
      - arm_wrist_left_yaw
  - name: fake_head_controller
    joints:
      - head_yaw
      - head_roll
